apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: obj-detect 
  janus-idp.io/tekton: obj-detect
  backstage.io/kubernetes-id: obj-detect
  backstage.io/kubernetes-namespace: rhdh-app 
  app.kubernetes.io/part-of: obj-detect
resources: 
- application-dev.yaml