apiVersion: batch/v1
kind: Job
metadata:
  name: dsp-clone-job-obj-detect-gitops
spec:  
  template:         
    metadata:
      name: dsp-clone-job-obj-detect-gitops
    spec:  
      serviceAccountName: obj-detect-dsp-job
      containers:
      - name: initialize-dsp
        image: quay.io/redhat-ai-dev/utils:latest
        command:
        - /bin/bash
        - -c
        - |
          NS=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)
          oc wait -l statefulset=obj-detect-notebook --for=condition=ready pod --timeout=300s
          oc exec  StatefulSet/obj-detect-notebook -- git clone https://github.com/gabemontero-appstudio-test-org/obj-detect
      restartPolicy: Never