---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: obj-detect
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: obj-detect 
  name: obj-detect
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi